spring:
  application:
    name: fooddiary
  modulith:
    runtime:
      flyway-enabled: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 1MB

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  flyway:
    enabled: false

  profiles:
    active: local

app:
  storage:
    location: ./uploads
    max-size: 5242880
    allow-types:
      - image/jpeg
      - image/png
      - image/webp
      - image/gif
